"""001_initial_schema

Revision ID: d2d49781270c
Revises:
Create Date: 2025-12-31 08:35:18.755534

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2d49781270c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color_variant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "function_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_function_types_is_active"),
        "function_types",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_function_types_name"), "function_types", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_function_types_slug"), "function_types", ["slug"], unique=True
    )
    op.create_table(
        "ideas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_alt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("problem", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("solution", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_users", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "key_features", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "prd_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("function_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("industry_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "target_user_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("popularity_score", sa.Integer(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("forked_from_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["forked_from_id"],
            ["ideas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ideas_created_by_id"), "ideas", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_ideas_forked_from_id"), "ideas", ["forked_from_id"], unique=False
    )
    op.create_index(
        op.f("ix_ideas_function_slug"), "ideas", ["function_slug"], unique=False
    )
    op.create_index(
        op.f("ix_ideas_industry_slug"), "ideas", ["industry_slug"], unique=False
    )
    op.create_index(op.f("ix_ideas_slug"), "ideas", ["slug"], unique=True)
    op.create_index(
        op.f("ix_ideas_target_user_slug"), "ideas", ["target_user_slug"], unique=False
    )
    op.create_index(op.f("ix_ideas_title"), "ideas", ["title"], unique=False)
    op.create_table(
        "industry_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_industry_types_is_active"),
        "industry_types",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_industry_types_name"), "industry_types", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_industry_types_slug"), "industry_types", ["slug"], unique=True
    )
    op.create_table(
        "target_user_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_user_types_is_active"),
        "target_user_types",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_target_user_types_name"), "target_user_types", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_target_user_types_slug"), "target_user_types", ["slug"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "hashed_password",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "google_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "avatar_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True
        ),
        sa.Column(
            "subscription_tier",
            sa.Enum("FREE", "PRO", "ENTERPRISE", name="subscriptiontier"),
            nullable=False,
        ),
        sa.Column("generation_credits", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_table(
        "idea_categories",
        sa.Column("idea_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["idea_id"], ["ideas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("idea_id", "category_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idea_categories")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_target_user_types_slug"), table_name="target_user_types")
    op.drop_index(op.f("ix_target_user_types_name"), table_name="target_user_types")
    op.drop_index(
        op.f("ix_target_user_types_is_active"), table_name="target_user_types"
    )
    op.drop_table("target_user_types")
    op.drop_index(op.f("ix_industry_types_slug"), table_name="industry_types")
    op.drop_index(op.f("ix_industry_types_name"), table_name="industry_types")
    op.drop_index(op.f("ix_industry_types_is_active"), table_name="industry_types")
    op.drop_table("industry_types")
    op.drop_index(op.f("ix_ideas_title"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_target_user_slug"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_slug"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_industry_slug"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_function_slug"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_forked_from_id"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_created_by_id"), table_name="ideas")
    op.drop_table("ideas")
    op.drop_index(op.f("ix_function_types_slug"), table_name="function_types")
    op.drop_index(op.f("ix_function_types_name"), table_name="function_types")
    op.drop_index(op.f("ix_function_types_is_active"), table_name="function_types")
    op.drop_table("function_types")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
