"""
LangGraph state definitions for the idea generation pipeline.

Defines the state schema that flows through the graph nodes.
"""

from typing import Annotated, Any, Optional
from typing_extensions import TypedDict

import operator


class IdeaConcept(TypedDict):
    """Initial idea concept generated by the first node."""

    title: str
    problem: str
    solution: str
    target_users: str
    key_features: list[str]


class PRDContent(TypedDict):
    """Full PRD content structure."""

    executive_summary: str
    problem_definition: str
    market_analysis: str
    user_personas: list[dict[str, str]]
    features: list[dict[str, str]]
    tech_stack: dict[str, list[str]]
    mvp_roadmap: list[dict[str, str]]
    success_metrics: list[dict[str, str]]


class GeneratedIdea(TypedDict):
    """Complete generated idea with all fields."""

    title: str
    problem: str
    solution: str
    target_users: str
    key_features: list[str]
    prd_content: PRDContent
    categories: list[str]


class IdeaGenerationState(TypedDict):
    """State for the idea generation pipeline.

    This state flows through all nodes in the graph:
    1. generate_concept: Creates initial idea concept
    2. expand_prd: Expands concept into full PRD
    3. categorize: Assigns categories
    4. save: Persists to database

    Attributes:
        run_id: Unique identifier for this generation run
        idea_index: Index of current idea (0-based) in multi-idea runs
        available_categories: List of category slugs from database
        concept: Initial idea concept
        prd_content: Expanded PRD content
        categories: Assigned category slugs
        idea_id: Database ID after saving (None until saved)
        error: Error message if any step fails
        completed: Whether pipeline completed successfully
    """

    # Run metadata
    run_id: str
    idea_index: int
    available_categories: list[str]

    # Pipeline outputs (populated progressively)
    concept: Optional[IdeaConcept]
    prd_content: Optional[PRDContent]
    categories: Optional[list[str]]

    # Final state
    idea_id: Optional[int]
    error: Optional[str]
    completed: bool


def create_initial_state(
    run_id: str,
    idea_index: int,
    available_categories: list[str],
) -> IdeaGenerationState:
    """Create initial state for a new idea generation.

    Args:
        run_id: Unique run identifier
        idea_index: Index of this idea in the batch
        available_categories: Available category slugs

    Returns:
        Initial state for the pipeline
    """
    return IdeaGenerationState(
        run_id=run_id,
        idea_index=idea_index,
        available_categories=available_categories,
        concept=None,
        prd_content=None,
        categories=None,
        idea_id=None,
        error=None,
        completed=False,
    )
