"""initial_schema

Revision ID: a31dbf9701cd
Revises:
Create Date: 2026-02-22 10:58:14.741543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a31dbf9701cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # -- Extensions --
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # -- Utility functions --
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_post_search_vector()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.search_vector = to_tsvector('english',
                coalesce(NEW.title, '') || ' ' || coalesce(NEW.body, '')
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)

    # -- Tables (autogenerated + manual additions) --
    op.create_table('cluster',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('post_count', sa.Integer(), nullable=False),
        sa.Column('label', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("status IN ('active', 'merged', 'archived')", name='chk_cluster_status'),
        sa.CheckConstraint('post_count >= 0', name='chk_cluster_post_count'),
    )
    op.create_table('post',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('external_created_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('num_comments', sa.Integer(), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('external_id', sa.Text(), nullable=False),
        sa.Column('subreddit', sa.Text(), nullable=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('external_url', sa.Text(), nullable=False),
        sa.Column('post_type', sa.Text(), nullable=True),
        sa.Column('sentiment', sa.Text(), nullable=True),
        sa.Column('tagging_status', sa.Text(), nullable=False),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source', 'external_id', name='uq_post_source_external_id'),
        sa.CheckConstraint("source IN ('reddit', 'app_store', 'play_store')", name='chk_post_source'),
        sa.CheckConstraint(
            "post_type IS NULL OR post_type IN ('complaint', 'feature_request', 'question', 'discussion', 'other')",
            name='chk_post_type',
        ),
        sa.CheckConstraint(
            "sentiment IS NULL OR sentiment IN ('positive', 'negative', 'neutral', 'mixed')",
            name='chk_post_sentiment',
        ),
        sa.CheckConstraint(
            "tagging_status IN ('pending', 'tagged', 'failed')",
            name='chk_post_tagging_status',
        ),
    )
    op.create_table('product',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('launched_at', sa.DateTime(), nullable=True),
        sa.Column('complaint_count', sa.Integer(), nullable=False),
        sa.Column('trending_score', sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('external_id', sa.Text(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('slug', sa.Text(), nullable=False),
        sa.Column('tagline', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('category', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_product_slug'),
        sa.UniqueConstraint('source', 'external_id', name='uq_product_source_external_id'),
        sa.CheckConstraint("source IN ('producthunt')", name='chk_product_source'),
        sa.CheckConstraint("char_length(slug) BETWEEN 1 AND 200", name='chk_product_slug_length'),
        sa.CheckConstraint("char_length(external_id) BETWEEN 1 AND 500", name='chk_product_external_id_length'),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 500", name='chk_product_name_length'),
        sa.CheckConstraint('complaint_count >= 0', name='chk_product_complaint_count'),
        sa.CheckConstraint(
            "trending_score >= 0 AND trending_score < 'Infinity'::NUMERIC",
            name='chk_product_trending_score',
        ),
        sa.CheckConstraint("url IS NULL OR url ~ '^https?://'", name='chk_product_url_scheme'),
        sa.CheckConstraint("image_url IS NULL OR image_url ~ '^https?://'", name='chk_product_image_url_scheme'),
    )
    op.create_table('tag',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('slug', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_tag_name'),
        sa.UniqueConstraint('slug', name='uq_tag_slug'),
        sa.CheckConstraint('char_length(name) BETWEEN 1 AND 100', name='chk_tag_name_length'),
        sa.CheckConstraint('char_length(slug) BETWEEN 1 AND 100', name='chk_tag_slug_length'),
    )
    op.create_table('brief',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('cluster_id', sa.BigInteger(), nullable=True),
        sa.Column('source_count', sa.Integer(), nullable=False),
        sa.Column('upvote_count', sa.Integer(), nullable=False),
        sa.Column('downvote_count', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('slug', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('problem_statement', sa.Text(), nullable=False),
        sa.Column('opportunity', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('demand_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('solution_directions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('source_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_brief_slug'),
        sa.CheckConstraint("status IN ('pending', 'published', 'archived')", name='chk_brief_status'),
        sa.CheckConstraint('char_length(slug) BETWEEN 1 AND 200', name='chk_brief_slug_length'),
        sa.CheckConstraint('source_count >= 0', name='chk_brief_source_count'),
        sa.CheckConstraint('upvote_count >= 0', name='chk_brief_upvote_count'),
        sa.CheckConstraint('downvote_count >= 0', name='chk_brief_downvote_count'),
    )
    op.create_table('cluster_post',
        sa.Column('cluster_id', sa.BigInteger(), nullable=False),
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id']),
        sa.ForeignKeyConstraint(['post_id'], ['post.id']),
        sa.PrimaryKeyConstraint('cluster_id', 'post_id'),
    )
    op.create_table('post_tag',
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.Column('tag_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['post.id']),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id']),
        sa.PrimaryKeyConstraint('post_id', 'tag_id'),
    )
    op.create_table('product_post',
        sa.Column('product_id', sa.BigInteger(), nullable=False),
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['post.id']),
        sa.ForeignKeyConstraint(['product_id'], ['product.id']),
        sa.PrimaryKeyConstraint('product_id', 'post_id'),
    )
    op.create_table('brief_source',
        sa.Column('brief_id', sa.BigInteger(), nullable=False),
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.Column('snippet', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['brief_id'], ['brief.id']),
        sa.ForeignKeyConstraint(['post_id'], ['post.id']),
        sa.PrimaryKeyConstraint('brief_id', 'post_id'),
    )
    op.create_table('rating',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('brief_id', sa.BigInteger(), nullable=False),
        sa.Column('is_positive', sa.Boolean(), nullable=False),
        sa.Column('session_id', sa.Text(), nullable=False),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['brief_id'], ['brief.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('brief_id', 'session_id', name='uq_rating_brief_session'),
        sa.CheckConstraint('char_length(session_id) BETWEEN 1 AND 255', name='chk_rating_session_id_length'),
        sa.CheckConstraint(
            'feedback IS NULL OR char_length(feedback) <= 1000',
            name='chk_rating_feedback_length',
        ),
    )

    # -- Triggers --
    op.execute("""
        CREATE TRIGGER trg_post_updated_at
            BEFORE UPDATE ON post
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_cluster_updated_at
            BEFORE UPDATE ON cluster
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_brief_updated_at
            BEFORE UPDATE ON brief
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_product_updated_at
            BEFORE UPDATE ON product
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_post_search_vector
            BEFORE INSERT OR UPDATE OF title, body ON post
            FOR EACH ROW EXECUTE FUNCTION fn_post_search_vector()
    """)

    # -- Indexes --
    op.execute("""
        CREATE INDEX idx_post_feed ON post (external_created_at DESC, id DESC)
            WHERE deleted_at IS NULL
    """)
    op.execute("""
        CREATE INDEX idx_post_subreddit ON post (subreddit, external_created_at DESC)
            WHERE deleted_at IS NULL
    """)
    op.execute("""
        CREATE INDEX idx_post_search_vector ON post USING GIN (search_vector)
            WHERE deleted_at IS NULL
    """)
    op.execute("""
        CREATE INDEX idx_post_title_trgm ON post USING GIN (title gin_trgm_ops)
            WHERE deleted_at IS NULL
    """)
    op.execute("""
        CREATE INDEX idx_post_tagging_pending ON post (created_at)
            WHERE tagging_status = 'pending'
    """)
    op.create_index('idx_post_tag_tag_id', 'post_tag', ['tag_id'])
    op.create_index('idx_cluster_post_post_id', 'cluster_post', ['post_id'])
    op.execute("""
        CREATE INDEX idx_cluster_active ON cluster (updated_at DESC)
            WHERE status = 'active'
    """)
    op.execute("""
        CREATE INDEX idx_brief_published ON brief (published_at DESC, id DESC)
            WHERE status = 'published'
    """)
    op.create_index('idx_brief_cluster_id', 'brief', ['cluster_id'])
    op.create_index('idx_brief_source_post_id', 'brief_source', ['post_id'])
    op.create_index('idx_product_trending', 'product', [sa.text('trending_score DESC'), sa.text('id DESC')])
    op.create_index('idx_product_complaints', 'product', [sa.text('complaint_count DESC'), sa.text('id DESC')])
    op.execute("""
        CREATE INDEX idx_product_launched ON product (launched_at DESC, id DESC)
            WHERE launched_at IS NOT NULL
    """)
    op.create_index('idx_product_post_post_id', 'product_post', ['post_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('rating')
    op.drop_table('brief_source')
    op.drop_table('product_post')
    op.drop_table('post_tag')
    op.drop_table('cluster_post')
    op.drop_table('brief')
    op.drop_table('tag')
    op.drop_table('product')
    op.drop_table('post')
    op.drop_table('cluster')

    op.execute("DROP FUNCTION IF EXISTS fn_post_search_vector()")
    op.execute("DROP FUNCTION IF EXISTS fn_set_updated_at()")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
